# Generated by Django 4.1.3 on 2022-12-11 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='discussione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_discussione', to='forum_app.discussione'),
        ),
    ]
